import { Jost } from "next/font/google";
import "./globals.css";
import { GlobalProvider } from "@/context/context";
import Navbar from "@/component/Navbar";

const jost = Jost({ subsets: ["latin"] });

export const metadata = {
  title: "EdgeMall App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <GlobalProvider>
          <Navbar />
          {children}
        </GlobalProvider>
      </body>
    </html>
  );
}
